version: '3.9'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
      - '3003:3003'
    environment:
      - TCP_HOST=127.0.0.1
      - TCP_PORT=3001
      - HTTP_PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULL_BOARD_PORT=3003
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server
